FROM centos
LABEL Anith <anith.swamy@gmail.com>

# Add repo file
#ADD ./ttt.repo /etc/yum.repos.d/

#install nmap software
RUN yum --assumeyes update && \
yum --assumeyes install \
nmap iproute && \
bash && \
yum clean all

CMD ["/usr/bin/nmap", "-sn", "172.17.0.0/24"]
